### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by notpushkin** [Songbee/meta#1]
- [x] Stream audio from torrent files
  - [x] Magnet link support
  - [ ] TorCache support (probably not needed)
- [x] Database (aka Tracker)
  - [ ] Plain server-side (partial progress)
    - [ ] Host it somewhere?
      - [ ] Plain cloud
      - [ ] Tor
    - [ ] Deployment (how?)
  - [ ] Federation
  - [ ] P2P (no ideas at all)
- [ ] More client-side things
  - [x] The UI™ (basic stuff works, but we also need:)
    - [ ] More routes
    - [ ] Working toolbar
  - [ ] Playlists
  - [ ] Probably more addons, like scrobbling or [This is my jam](http://timj.am) support
  - [ ] How about switching to Atom Shell? Discuss that.

**Comment by notpushkin** [comment]
This is outdated now, look at https://github.com/Songbee/desktop/issues and https://github.com/Songbee/tracker/issues instead.
